### ISSUE TITLE
rest_api_gcbm build is broken

### ISSUE THREAD

**Issue by aornugent** [moja-global/FLINT.Cloud#106]
Reported in https://github.com/moja-global/FLINT-UI/issues/258 and on Slack - there seems to be something wrong with the integration of moja.canada into our GCBM endpoints. 

The last known working version was https://github.com/moja-global/FLINT.Cloud/pull/63 but CI was not configured at this time. @HarshCasper - I believe you manually pushed a copy from a forked repository, but it's hard to tell which image it was. 

The issue may have occured in #65, #70 or  https://github.com/moja-global/FLINT.Cloud/pull/88, and it is not clear what the differences between these builds are. The mono-Dockerfile in #63 moved some Poco build arguments into the `base` image which are recreated in moja.canada - which may be the culprit (but also may not be).

Help dissecting out these changes is very much appreciated.

**Comment by Namyalg** [comment]
This is a file containing the various SHAs of the moja.canada image in chronological order
It might help in checking which build was working as expected

[canada.csv](https://github.com/moja-global/FLINT.Cloud/files/8612755/canada.csv)

**Comment by aornugent** [comment]
@Namyalg - Harsh has reported a functioning build from March on [his fork](https://github.com/HarshCasper/FLINT.Cloud/commits/master). We might be able to zero in on packages published around this time.

**Comment by Namyalg** [comment]
Alright, will check

**Comment by aornugent** [comment]
@HarshCasper - issues with the `flint.gcbm` image have been resolved but our build pipeline is not yet functional. Can you please help me debug?

**Comment by aornugent** [comment]
This was a super unhelpful failure mode: https://github.com/moja-global/FLINT.Cloud/actions/runs/2365459825

If it's a memory overflow, perhaps we need to somehow prune the base image? @Namyalg - you encountered some strange behaviour with your local builds that were resolved by reducing the number of concurrent threads?

**Comment by Namyalg** [comment]
Yes, explicitly passing NUM_CPU as 1, resolved it

**Comment by aornugent** [comment]
@HarshCasper has manually pushed a copy of `flint.gcbm` and our CI for `rest_api_gcbm` now functions. This creates a manual bottleneck in an otherwise automated pipeline, but it is manageable for now. We will update the GitHub Actions (GHA) workflow to build the `flint.gcbm` image when we have resolved the issues of building on small memory GHA Runners,
