### ISSUE TITLE
Implement the pre-processing script for new GCBM simulation

### ISSUE THREAD

**Issue by padmajabhol** [moja-global/FLINT.Cloud#110]
The `/upload` endpoint present in the [rest_api_gcmb](https://github.com/moja-global/FLINT.Cloud/blob/master/local/rest_api_gcbm/app.py#L157) accepts inputs present in the [GCBM_Demo_Run](https://github.com/moja-global/FLINT.Cloud/blob/master/GCBM_Demo_Run.zip). 

The [pre-processing script](https://github.com/padmajabhol/LFX-mentorship-progress-tracker/blob/main/GCBM_Demo_Run/config/app.py) generates all the JSON files present in the `/config` folder. 

The pre-processing script has three folders, one meant for the JSON and tiff files for `Classifiers,` one for `disturbances`, and one for `annual_mean_temperature` and `initial_age`.  Based on this, we are planning to have three endpoints: `/classifiers`, `/disturbances`, `/miscellaneous` and `/database` (for the mapping --> `spinup.json` & `variables.json`.

In the end, it should look something like this:

```
inputs/
         name-of-simulation
                 disturbances
                 classifiers
                 miscellaneous
```

Though we are trying to generate all the JSONs that are being used as inputs, we were quite unsure about having to deal with the JSON files present in the `/layers/tiled` folder(since most of them are boilerplate but still can be parsed from their respective tiff files using raster objects). We will include that in the script as well.

@Namyalg has already proposed an API design for the configuration of the tables (from the SQL DB file) [here](https://github.com/Namyalg/gcbm-table-schema). We shall be pushing our code to this particular repository trying to implement a basic design and later wrap it up for FLINT.Cloud.

CC: @aornugent @Namyalg

**Comment by Namyalg** [comment]
In addition to the above endpoints, we can have a `/download-config` to get the config files used for the simulation
