### ISSUE TITLE
/gcbm/download api is working even for non-exist simulation title and returns a corrupted output.zip file.

### ISSUE THREAD

**Issue by AayushSaini101** [moja-global/FLINT.Cloud#126]
**/gcbm/download** api is working even for non-exist simulation titles and returns a corrupted output.zip file.

There is only **run4** simulation is present, but it is producing the simulation for the "run47" title (This is not created)
![new](https://user-images.githubusercontent.com/60972989/171982555-5377e573-eecf-4aaf-a755-d916afcdd5cf.PNG)

**Output.zip**

![new](https://user-images.githubusercontent.com/60972989/171982625-bc0d9c29-f4da-4ed1-a51d-81c7b9aa5f0d.PNG)

**Comment by Crystalsage** [comment]
If this hasn't been fixed already - can I work on this?

**Comment by temitayopelumi** [comment]
@Namyalg, @aornugent  can I work on this issue?

**Comment by aornugent** [comment]
@temitayopelumi - can you please describe your solution in broad strokes? How will you fix it?

**Comment by temitayopelumi** [comment]
@aornugent, 
If a successful simulation exists, the output file should be in the folder app/output
So,
1. I will check if the title has a corresponding output in the output folder.
2. I will return the current response if it has an output.
3. If it does not, I will return "You don't have a simulation with this title kindly check the title and try again."

**Comment by temitayopelumi** [comment]
<img width="438" alt="Screen Shot 2022-10-16 at 11 42 24 AM" src="https://user-images.githubusercontent.com/47720307/196030983-916c6eaf-2b37-4e0d-80ef-91825caff4c3.png">
 The current code is not checking if the output exists

**Comment by aornugent** [comment]
Sounds great, please go ahead.

**Comment by temitayopelumi** [comment]
Alright

**Comment by temitayopelumi** [comment]
@aornugent  I have raised a PR for this. But the labeller keeps failing. Do you know what could be wrong?
