### ISSUE TITLE
The swagger.json file of the gcbm needs to update.

### ISSUE THREAD

**Issue by AayushSaini101** [moja-global/FLINT.Cloud#131]
Currently, the swagger.json file of the gcbm file contains the /rothc endpoint description. There is no endpoint of /rothc currently present for the rest api gcbm.

**Path of the file:**
`local\rest_api_gcbm\static\swagger.json`

![new](https://user-images.githubusercontent.com/60972989/173133147-6fe074d8-bf3e-45be-9c13-11a058e60126.JPG)

**Comment by SanjaySinghRajpoot** [comment]
I have texted @shubhamkarande13 for the same a while ago. lets see what views he has on this. There is also no API structure given for the APIs which needs to be updated.

**Comment by temitayopelumi** [comment]
Hi, @SanjaySinghRajpoot  has been finalized, can I work on it? I'm an outreach intern

**Comment by SanjaySinghRajpoot** [comment]
Yes you can work on this @temitayopelumi.

**Comment by temitayopelumi** [comment]
Alright. I will get to it

**Comment by temitayopelumi** [comment]
@SanjaySinghRajpoot  i have raised a PR for this.
