### ISSUE TITLE
cURL set-up for FLINT example

### ISSUE THREAD

**Issue by Namyalg** [moja-global/FLINT.Cloud#134]
Currently, the FLINT example does not have a cURL-based setup. The cURL setup will help users interact easily with the endpoints

**Comment by AayushSaini101** [comment]
@HarshCasper  Please assign this issue

**Comment by padmajabhol** [comment]
Hi @AayushSaini101 since you already have a pending issue, maybe someone else can take this up.

**Comment by Sukriti-sood** [comment]
@Namyalg @padmajabhol Can I work on this.
