### ISSUE TITLE
Wrong docstring for a GCBM simulation method

### ISSUE THREAD

**Issue by Crystalsage** [moja-global/FLINT.Cloud#146]
The docstring for the `gcbm_new()` method in GCBM API is meant for `gcbm_upload()` and seems to be duplicated from there.

https://github.com/moja-global/FLINT.Cloud/blob/089614d6f71911240d3f23250b45156432bddd0b/local/rest_api_gcbm/app.py#L131-L147

We should replace it with something meant for `gcbm_new()`.

**Comment by padmajabhol** [comment]
Do you want to take this up? @Crystalsage

**Comment by Crystalsage** [comment]
@padmajabhol Sure.
