### ISSUE TITLE
Issue template for FLINT.Cloud

### ISSUE THREAD

**Issue by SanjaySinghRajpoot** [moja-global/FLINT.Cloud#148]
There is no issue template present for FLINT. Cloud. With an issue template, a user will be able to provide more information in a structured manner. That will help us understand the issue. For reference, you can look at the FLINT-UI issue template. 

key point 
- Description
- Context 
- Changes 
- Additional Info

Thank You

**Comment by SanjaySinghRajpoot** [comment]
Good first issue.

**Comment by Crystalsage** [comment]
Can I work on this?

**Comment by sailorworks** [comment]
Hi, please assign this issue to me.

**Comment by padmajabhol** [comment]
Didn't notice we already had YAML templates, closing this now.
