### ISSUE TITLE
Change the endpoint name `/gcbm/dynamic` to `/gcbm/run`

### ISSUE THREAD

**Issue by padmajabhol** [moja-global/FLINT.Cloud#149]
Currently, the endpoint that runs the container does not have a meaningful name, we could like to rename it to something more meaningful. 
After you have made the required changes, please make sure you change the pytest for the same.

**Comment by Sukriti-sood** [comment]
@padmajabhol There exist already same issue and pr[pr](https://github.com/moja-global/FLINT.Cloud/pull/118) for it.
