### ISSUE TITLE
Add python packages to `flint.gcbm` Docker image

### ISSUE THREAD

**Issue by aornugent** [moja-global/FLINT.Cloud#155]
I've been exploring @radistoubalidis's work on the GCBM.Belize repository and would like to add two upstream dependencies to our `flint.gcbm` docker image:

* DVC - `pip install dvc`
* mojadata -  `pip install git+https://github.com/moja-global/GCBM.Data#subdirectory=mojadata`

These should be small changes to `docker/Dockerfile.gcbm` but please test your build locally.

**Comment by padmajabhol** [comment]
@Sukriti-sood

**Comment by Sukriti-sood** [comment]
I would like to work on this issue.
