### ISSUE TITLE
Move the preprocessing functions ` get_config_templates`, ` get_modules_cbm_config`, `get_provider_config` to a separate file

### ISSUE THREAD

**Issue by Namyalg** [moja-global/FLINT.Cloud#170]
The above mentioned preprocessing functions are present in the file https://github.com/moja-global/FLINT.Cloud/blob/master/local/rest_api_gcbm/app.py
For ease of use and readability, it will be a good idea to shift these to a different file

**Comment by khanjasir90** [comment]
@Namyalg I would like to work on this!

**Comment by Namyalg** [comment]
Sure!

**Comment by khanjasir90** [comment]
@Namyalg should I name the new file as "util.py" or any other name you could suggest of?

**Comment by Namyalg** [comment]
How about `preprocess.py` ?

**Comment by khanjasir90** [comment]
ohh great! ig preprocess.py would be better.
