### ISSUE TITLE
Create an endpoint to return the `JSON` file generated in the backend

### ISSUE THREAD

**Issue by Namyalg** [moja-global/FLINT.Cloud#183]
In the current version of the GCBM simulation, the user is expected to upload only the `tiff` files as inputs. 
The JSON for the file is generated in the backend.
We require an endpoint that can return the generated JSON given an input tiff file name

Name of the endpoint  : `/getConfig` 
Method type : `POST`, taking the name of the simulation and name of the input file
Response : Generated JSON

**Comment by khanjasir90** [comment]
@Namyalg I'll take this one

**Comment by khanjasir90** [comment]
@Namyalg do i need to explicitly convert .tiff to json or is it being done when /dynamic request is being executed!

**Comment by khanjasir90** [comment]
@Namyalg do i need to use any specific package for the conversion or anything will do?

**Comment by Namyalg** [comment]
Hi, I'd suggest you take a look at the file `app.py` and the commits made previously.
Try out the simulation.
Inspect the docker container to see how the JSON configuration is generated

Do share your findings, preferably on the slack channel
