### ISSUE TITLE
Run the APIs for FLINT Example and tell us your findings/understandings.

### ISSUE THREAD

**Issue by padmajabhol** [moja-global/FLINT.Cloud#189]
You can find all the instructions for the Flask example REST API Setup in the repository readme. Instructions on how to run the APIs can be found here: https://github.com/moja-global/FLINT.Cloud/blob/master/local/rest_api_flint.example/curl.md

There's no restriction on how you could want to take this on. The findings draft doesn't have to be anything formal and can be like a paragraph where you could ELIF.

**Comment by legendarykamal** [comment]
@padmajabhol I am interested to execute this task.

**Comment by padmajabhol** [comment]
@legendarykamal this issue was not needed so I'm closing it for now, you can check other open issues.
