### ISSUE TITLE
Update curl commands for the GCBM simulation

### ISSUE THREAD

**Issue by SanjaySinghRajpoot** [moja-global/FLINT.Cloud#191]
The GCBM has been continually updated to make it more dynamic and flexible. Many endpoints were renamed for new features and updates. Some of the recent endpoints were added to the GCBM simulation(check GCBM app,py) but they were not documented for curl cmds. Added curl docs for the remaining APIs and text the existing curl cmds. 

Thank You

**Comment by legendarykamal** [comment]
hi @SanjaySinghRajpoot I would like to take this up :)

**Comment by SanjaySinghRajpoot** [comment]
please go ahead and send the PR.
