### ISSUE TITLE
Refactor `test_help_all` test-case for FLINT.Example REST API

### ISSUE THREAD

**Issue by HarshCasper** [moja-global/FLINT.Cloud#212]
## Description

Refactor the following test-case for different endpoints:

https://github.com/moja-global/FLINT.Cloud/blob/3692589a39505e296d7b525523a01b046b8f3a68/local/tests/test_rest_example.py#L28

**Comment by shivaylamba** [comment]
@HarshCasper Hey I would love to work on this issue, can you assign this issue
