### ISSUE TITLE
Design Dynamic GCBM api endpoint

### ISSUE THREAD

**Issue by Tlazypanda** [moja-global/FLINT.Cloud#5]
**Describe how we are communicating and why it is not optimal.**
As per the discussion on slack and from @mfellows and @aornugent suggestions, the gcbm endpoint has to be dynamic in nature. This entails all the - 

- config files: All files in config directory (.json and .cfg files)
- db: Input databse file (gcbm_input.db)
- input: All files in layers/tiled directory (.tif files)
 
 So the proposed solution is to have these as the parameters for the api endpoint and create a directory structure from this within the mounted volume (local run data shared by @mfellows). 
 
 Needs further discussion and work to properly perfect this to an extent that users find this pellucid.

**Comment by aornugent** [comment]
@Tlazypanda - I think we can close this, but please comment with a link to your documented design once it's written.
