### ISSUE TITLE
SQLite version needs to be updated

### ISSUE THREAD

**Issue by gchhablani** [moja-global/FLINT.Cloud#64]
Currently, the SQLite version is causing issues when running the GCBM Belize project inside a FLINT Cloud container. Newer functions lie RANK/PARTITION do not work with the old version.

See the [issue here](https://github.com/moja-global/GCBM.Belize/issues/5) for more details of the errors.

As discussed with @mfellows @aornugent on Slack, SQLite needs to be be updated to either this or a newer version:
https://www.sqlite.org/2018/sqlite-autoconf-3260000.tar.gz

**Comment by aornugent** [comment]
This is resolved on #63 but some minor changes need to be propagated upstream in [#28](https://github.com/moja-global/moja.canada/pull/28) and [116](https://github.com/moja-global/FLINT/pull/116)
