### ISSUE TITLE
Update instructions and format README for the GCBM REST API example setup

### ISSUE THREAD

**Issue by Namyalg** [moja-global/FLINT.Cloud#74]
- The instructions present https://github.com/moja-global/FLINT.Cloud/tree/master/local/rest_api_gcbm are not corresponding to the latest repository structure
- Store the endpoints in a tabular format similar to https://github.com/moja-global/FLINT.Cloud

**Comment by akashthedeveloper** [comment]
Would love to fix this issue?

**Comment by akashthedeveloper** [comment]
@HarshCasper Since, this issue is been solved I think the issue needs to be closed.
