### ISSUE TITLE
/point and /rothc taking too long to load

### ISSUE THREAD

**Issue by suvadityamuk** [moja-global/FLINT.Cloud#87]
I have been trying to set up `FLINT.Cloud` on my local machine to test around, and I was trying to run the `point` and `rothc` examples as per the README.md examples.
On using the endpoints, I am facing timeouts even after waiting for almost 10 minutes.

For context, here are some images of my command line from running the Docker commands and the Postman endpoints I am hitting. 

![image](https://user-images.githubusercontent.com/70141886/159289104-1513cdf5-564e-4796-9ca6-0724002b058a.png)

On using the `/help/all` endpoint, I do get a valid response, telling me that the 
![image](https://user-images.githubusercontent.com/70141886/159289230-c8677c40-c3f2-4bdb-b8ef-84bc7309492d.png)

Here is an image of Postman sending a request to the `/rothc` endpoint for the last 10 minutes.
![image](https://user-images.githubusercontent.com/70141886/159289320-fd51853f-3db1-4cf1-b40a-b5bb762a6d56.png)

Please advise on what to do in this case.

**Comment by Namyalg** [comment]
Hey, `/point` and `/rothc` are POST endpoints

**Comment by suvadityamuk** [comment]
Ahh. I understand, thank you very much for the help
