### ISSUE TITLE
Add npm to rest_api_gcbm Dockerfile for CML actions

### ISSUE THREAD

**Issue by aornugent** [moja-global/FLINT.Cloud#91]
We sometimes use this image for running automated tests. There's an example of our CML workflow here: https://github.com/moja-global/GCBM.Belize/pull/7

Because the rest_api_gcbm image just a light wrapper over the standard GCBM build, I think it's ok to add npm here and save the installing it in every workflow. Please add npm to the rest_api_gcbm Dockerfile.

**Comment by ankitaS11** [comment]
Hi @aornugent, My initial outreachy application got approved and was looking at the organization list, and found moja global doing some great work. I am looking forward to contribute to moja global. Is it okay, if I start of with this issue?

**Comment by chicken-biryani** [comment]
Hi, @ankitaS11 we've listed a few tasks on Slack in the #outreachy channel.

You could work on the issue... But then you won't be working in the required direction.

I understand that you have to report a contribution but making one in the right direction may help you better.

If you haven't joined our slack, please do so. You'll find the link in the Readme or under the community landing page (Outreachy/moja global.)
