### ISSUE TITLE
Enhance Contribution Section in the README

### ISSUE THREAD

**Issue by Namyalg** [moja-global/FLINT.Cloud#95]
Currently, the contribution section does not provide details about the commit/branch conventions followed. 
It can be made similar to : https://github.com/moja-global/FLINT-UI

**Comment by abant07** [comment]
Hi @Namyalg,

I'm new to Github, so I am not very familiar with all features and files, but I was wondering if you could elaborate more on the problem with the README file?

Thanks

**Comment by Namyalg** [comment]
Hey @abant07, as stated have a look at the README file for FLINT UI as linked above, and think about how the README of FLINT cloud can be improved.
To give more context on a README file, it provides information about a project, it's usage, contributing guidelines etc.

**Comment by abant07** [comment]
Hi @Namyalg 

So, I should just find things to add in README file of the FLINT cloud server by looking at the things in the FLINT UI server README file? If so, could I be assigned to this issue?

Thanks

**Comment by Namyalg** [comment]
Look at the FLINT UI README, and see how the FLINT Cloud README can improved and user-friendly. For instance, think of what a new contributor might want to know before making their first contribution 
@HarshCasper can assign this issue to you

**Comment by Iheanacho-ai** [comment]
hey good day please is this issue still opened to work on
