### ISSUE TITLE
Implement the `rest_api_flint.example` root endpoint

### ISSUE THREAD

**Issue by HarshCasper** [moja-global/FLINT.Cloud#96]
## Description

Add a root endpoint to the `rest_api_flint.example` API. It can be as simple as adding:

```sh
@app.route('/', methods=['GET'])
def home():
    return 'FLINT.Example API'
```

Test it on the Docker container and submit a patch.

**Comment by tolusolaadeyemi** [comment]
Hello @HarshCasper I would like to work on this issue that you suggested during the meeting.

**Comment by demigod-11** [comment]
hello @HarshCasper i would like to work on this 
please can you assign this issue to me

**Comment by HarshCasper** [comment]
It has already been merged!
