### ISSUE TITLE
Add `*.azurewebsites.net` to the CORS origin

### ISSUE THREAD

**Issue by HarshCasper** [moja-global/FLINT.Cloud#97]
## Description

Right now, we are getting CORS errors over the deployment of FLINT.Cloud and FLINT-UI. The error can be traced over to these references:

- FLINT.Example: https://github.com/moja-global/FLINT.Cloud/blob/da310e4efcd969c0dfe54f06f550fc2e37571571/local/rest_api_flint.example/app.py#L14
- REST API GCBM: https://github.com/moja-global/FLINT.Cloud/blob/da310e4efcd969c0dfe54f06f550fc2e37571571/local/rest_api_gcbm/app.py#L23

We need to add `*.azurewebsites.net` to this so that we can mitigate this issue.

**Comment by aornugent** [comment]
The CORS whitelist can be a deployment specific set of values. Perhaps we can stored the whitelist in an environment variable?

**Comment by tolusolaadeyemi** [comment]
Hi, I would like to work on this issue

**Comment by Ansh-Sarkar** [comment]
Hi ! Was just getting started with trying to understand the codebase. Just to confirm : We need to add ```*.azurewebsites.net``` to the above mentioned files in order to enable Cross Origin Requests right ?

If this issue is still open and nobody is working on it, I would surely like to work on it.

**Comment by baimamboukar** [comment]
Is this issue still valid ?

**Comment by HarshCasper** [comment]
Nope — It has been fixed.
